# Generated by Django 4.2.11 on 2026-04-19 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('high_contrast', 'High Contrast'), ('inverted', 'Inverted')], default='light', max_length=20)),
                ('text_size', models.CharField(choices=[('normal', 'Normal'), ('large', 'Large'), ('xlarge', 'Extra Large')], default='normal', max_length=20)),
                ('reduce_motion', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
