# Generated by Django 6.0.2 on 2026-03-16 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_address_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pending_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='pending_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CreditCard', 'CreditCard'), ('DebitCard', 'DebitCard')], max_length=20),
        ),
    ]
