# Generated by Django 6.0.2 on 2026-03-22 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_product_pending_description_product_pending_name_and_more'),
        ('shop', '0009_rename_price_when_ordered_orderitem_price_at_purchase_and_more'),
    ]

    operations = [
    ]
