# Generated by Django 6.0.2 on 2026-04-04 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_payout_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payout',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Refunded', 'Refunded')], default='Pending', max_length=20),
        ),
    ]
