# Generated by Django 4.2.11 on 2026-04-19 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('estimated_days_min', models.PositiveIntegerField(blank=True, null=True)),
                ('estimated_days_max', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingRateRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, max_length=50)),
                ('zip_prefix', models.CharField(blank=True, max_length=10)),
                ('extra_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_peak_time', models.BooleanField(default=False)),
                ('shipping_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='shop.shippingoption')),
            ],
        ),
    ]
