# Generated by Django 4.2.11 on 2026-04-19 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_shippingoption_shippingraterule'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.shippingoption'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_option_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.DeleteModel(
            name='ShippingRateRule',
        ),
    ]
